# Generated by Django 4.0.6 on 2022-07-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.CharField(default=(1, 0, 0), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='sqft',
            field=models.CharField(max_length=100),
        ),
    ]
