# Generated by Django 4.0.6 on 2022-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_home_price_alter_home_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
