# Generated by Django 4.0.6 on 2022-07-12 21:31

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_home_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
